### PR TITLE
SCSS(Sassy CSS) is a syntax for Sass and should be "Sass."

### PR DESCRIPTION
**Pull request by brianmontanaweb**
Lemme know if you want this edited :)

Reference:

https://twitter.com/hcatlin/status/394555738636296192
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax

### CODE REVIEW

**Comment by unruledboy** [comment]
Thanks mate

**Comment by brianmontanaweb** [comment]
No problem! :)

**Comment by unruledboy** [comment]
Wow, you are quick, I just got up.

Do you want to be contributor?

**Comment by brianmontanaweb** [comment]
Yesss! I'm in Chicago, so it's evening now.

**Pull request merged**
