### PR TITLE
Competes with Handlebars but {{ mustache }} is logic-less.

### PR DESCRIPTION
**Pull request by brianmontanaweb**
I've seen a few debates between Handlebars and {{ mustache }}

### CODE REVIEW

**Comment by zsxsoft** [comment]
Why not rebuild the image and the readme?

**Comment by brianmontanaweb** [comment]
I'll build it, I think @unruledboy or you did that.

**Comment by zsxsoft** [comment]
Just because I'm lazy.. LOL 
 _ (:з」∠) _

**Comment by brianmontanaweb** [comment]
LOL I should learn how to build it anyway :)

**Comment by zsxsoft** [comment]
It's easy to build but it's hard to prepare for the environment, you should have your mind aware of what's going on next. LOL

**Comment by brianmontanaweb** [comment]
Update with image and README, looks good to me, wanna make sure before I merge :)

**Pull request merged**
